In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('weatherAUS.csv.zip')
df.head()

         Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No
1  2008-12-02   Albury      7.4  ...     24.3         No            No
2  2008-12-03   Albury     12.9  ...     23.2         No            No
3  2008-12-04   Albury      9.2  ...     26.5         No            No
4  2008-12-05   Albury     17.5  ...     29.7         No            No

[5 rows x 23 columns]

In [6]:
df.shape

(145460, 23)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  str
 1   Location       145460 non-null  str
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  str
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  str
 10  WindDir3pm     141232 non-null  str
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: float64(16), str(7)
memory usage: 29.7 MB

In [8]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     110316
Yes     31877
Name: count, dtype: int64

In [9]:
df = df.dropna(subset=['RainTomorrow'])

In [10]:
df.shape

(142193, 23)

In [11]:
df['RainToday'] = df['RainToday'].map({'No':0, 'Yes':1})
df['RainTomorrow'] = df['RainTomorrow'].map({'No':0, 'Yes':1})

In [12]:
X = df.drop(['RainTomorrow'], axis=1)
y = df['RainTomorrow']

In [13]:
X.head()

         Date Location  MinTemp  MaxTemp  ...  Cloud3pm  Temp9am  Temp3pm RainToday
0  2008-12-01   Albury     13.4     22.9  ...       NaN     16.9     21.8       0.0
1  2008-12-02   Albury      7.4     25.1  ...       NaN     17.2     24.3       0.0
2  2008-12-03   Albury     12.9     25.7  ...       2.0     21.0     23.2       0.0
3  2008-12-04   Albury      9.2     28.0  ...       NaN     18.1     26.5       0.0
4  2008-12-05   Albury     17.5     32.3  ...       8.0     17.8     29.7       0.0

[5 rows x 22 columns]

In [14]:
X.shape

(142193, 22)

In [15]:
y.head(6)

0    0
1    0
2    0
3    0
4    0
5    0
Name: RainTomorrow, dtype: int64

In [16]:
y.shape

(142193,)

In [17]:
X.dtypes.value_counts()

float64    17
str         5
Name: count, dtype: int64

In [18]:
num_cols = X.select_dtypes(include=np.number).columns
cat_cols = X.select_dtypes(include = 'str').columns

In [19]:
num_cols

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday'],
      dtype='str')

In [20]:
cat_cols

Index(['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm'], dtype='str')

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [22]:
num_transformer = Pipeline([
                ('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())
])

In [23]:
cat_transformer = Pipeline([
                ('imputer', SimpleImputer(strategy='most_frequent')),
                ('OHE', OneHotEncoder(handle_unknown='ignore'))
])

In [24]:
preprocessor = ColumnTransformer([
            ('num', num_transformer, num_cols),
            ('cat', cat_transformer, cat_cols)
])

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [27]:
random_forest = RandomForestClassifier(n_estimators=200, random_state=42, max_depth=10,
                                         min_samples_split=5, min_samples_leaf=2)

In [28]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', random_forest)    
])

In [29]:
print('done')

done

In [30]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       '...y'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OHE',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm'], dtype='str'))])),
                ('classifier',
                 RandomForestClassifier(max_depth=10, min_samples_leaf=2,
                                        min_samples_split=5, n_estimators=200,
                                        random_state=42))])

In [31]:
y_pred = model.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

In [33]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7787193642533141
              precision    recall  f1-score   support

           0       0.78      1.00      0.88     22064
           1       0.99      0.01      0.03      6375

    accuracy                           0.78     28439
   macro avg       0.88      0.51      0.45     28439
weighted avg       0.83      0.78      0.68     28439

In [34]:
df.corr(numeric_only=True)['RainTomorrow'].sort_values(ascending=False)

RainTomorrow     1.000000
Humidity3pm      0.446160
Cloud3pm         0.381870
Cloud9am         0.317380
RainToday        0.313097
Humidity9am      0.257161
Rainfall         0.239032
WindGustSpeed    0.234010
WindSpeed9am     0.090995
WindSpeed3pm     0.087817
MinTemp          0.083936
Temp9am         -0.025691
Evaporation     -0.119285
MaxTemp         -0.159237
Temp3pm         -0.192424
Pressure3pm     -0.226031
Pressure9am     -0.246371
Sunshine        -0.450768
Name: RainTomorrow, dtype: float64

In [37]:
from sklearn.feature_selection import _rfe

In [40]:
feature_names = model.named_steps['preprocessor'].get_feature_names_out()

In [39]:
rf = model.named_steps["classifier"]

In [44]:
importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(by="importance", ascending=False)

print(importance_df.head(20))

                         feature  importance
9               num__Humidity3pm    0.148997
16                num__RainToday    0.097182
2                  num__Rainfall    0.089095
4                  num__Sunshine    0.074181
10              num__Pressure9am    0.071007
13                 num__Cloud3pm    0.067833
12                 num__Cloud9am    0.057038
8               num__Humidity9am    0.056683
5             num__WindGustSpeed    0.044032
11              num__Pressure3pm    0.039810
15                  num__Temp3pm    0.038165
1                   num__MaxTemp    0.029282
0                   num__MinTemp    0.015663
3               num__Evaporation    0.013919
7              num__WindSpeed3pm    0.011443
6              num__WindSpeed9am    0.009005
14                  num__Temp9am    0.008961
3431  cat__Location_AliceSprings    0.003638
3499         cat__WindDir9am_NNW    0.003626
3476       cat__Location_Woomera    0.003594

In [43]:
top_k = 10

In [49]:
selected_features = importance_df.head(top_k)['feature'].values
selected_features.tolist()

['num__Humidity3pm',
 'num__RainToday',
 'num__Rainfall',
 'num__Sunshine',
 'num__Pressure9am',
 'num__Cloud3pm',
 'num__Cloud9am',
 'num__Humidity9am',
 'num__WindGustSpeed',
 'num__Pressure3pm']

In [51]:
top_10_features = importance_df.sort_values( "importance", ascending=False)["feature"].head(10).tolist()

In [52]:
X_train_trans = model.named_steps["preprocessor"].transform(X_train)
X_test_trans = model.named_steps["preprocessor"].transform(X_test)

In [53]:
feature_names = model.named_steps["preprocessor"].get_feature_names_out()

In [54]:
selected_idx = [np.where(feature_names == f)[0][0] for f in top_10_features]
selected_idx

[np.int64(9),
 np.int64(16),
 np.int64(2),
 np.int64(4),
 np.int64(10),
 np.int64(13),
 np.int64(12),
 np.int64(8),
 np.int64(5),
 np.int64(11)]

In [55]:
X_train_top10 = X_train_trans[:, selected_idx]
X_test_top10 = X_test_trans[:, selected_idx]

In [56]:
final_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_leaf=5,
    random_state=42)

final_model.fit(X_train_top10, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=5, random_state=42)

In [57]:
Y_pred = final_model.predict(X_test_top10)

print("Accuracy:", accuracy_score(y_test, Y_pred))

Accuracy: 0.8477091318260136

In [58]:
print(classification_report(y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     22064
           1       0.76      0.47      0.58      6375

    accuracy                           0.85     28439
   macro avg       0.81      0.71      0.74     28439
weighted avg       0.84      0.85      0.83     28439

In [60]:
import joblib
joblib.dump(final_model, 'weather_model.pkl')

['weather_model.pkl']

In [61]:
import os

In [62]:
print(os.path.getsize('weather_model.pkl'),'bytes')

11357433 bytes